//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: fight.proto
// Note: requires additional types generated from: common.proto
namespace clientmsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestFindOpp")]
  public partial class RequestFindOpp : global::ProtoBuf.IExtensible
  {
    public RequestFindOpp() {}
    

    private uint _oppid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"oppid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint oppid
    {
      get { return _oppid; }
      set { _oppid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserRequestFight")]
  public partial class UserRequestFight : global::ProtoBuf.IExtensible
  {
    public UserRequestFight() {}
    

    private clientmsg.FightT _type = clientmsg.FightT.PVE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(clientmsg.FightT.PVE)]
    public clientmsg.FightT type
    {
      get { return _type; }
      set { _type = value; }
    }

    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }

    private uint _positionid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"positionid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint positionid
    {
      get { return _positionid; }
      set { _positionid = value; }
    }

    private uint _fromuaid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fromuaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fromuaid
    {
      get { return _fromuaid; }
      set { _fromuaid = value; }
    }

    private uint _touaid = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"touaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint touaid
    {
      get { return _touaid; }
      set { _touaid = value; }
    }

    private uint _autoresult = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"autoresult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint autoresult
    {
      get { return _autoresult; }
      set { _autoresult = value; }
    }

    private uint _revenge = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"revenge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint revenge
    {
      get { return _revenge; }
      set { _revenge = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameUserRequestFight")]
  public partial class GameUserRequestFight : global::ProtoBuf.IExtensible
  {
    public GameUserRequestFight() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DBRequestFindOpp")]
  public partial class DBRequestFindOpp : global::ProtoBuf.IExtensible
  {
    public DBRequestFindOpp() {}
    

    private uint _gameid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gameid
    {
      get { return _gameid; }
      set { _gameid = value; }
    }

    private uint _gateoid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gateoid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gateoid
    {
      get { return _gateoid; }
      set { _gateoid = value; }
    }

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private uint _trophy = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"trophy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint trophy
    {
      get { return _trophy; }
      set { _trophy = value; }
    }

    private uint _oppid = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"oppid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint oppid
    {
      get { return _oppid; }
      set { _oppid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillData")]
  public partial class SkillData : global::ProtoBuf.IExtensible
  {
    public SkillData() {}
    

    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private uint _location = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint location
    {
      get { return _location; }
      set { _location = value; }
    }

    private uint _number = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint number
    {
      get { return _number; }
      set { _number = value; }
    }

    private uint _advanced = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"advanced", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint advanced
    {
      get { return _advanced; }
      set { _advanced = value; }
    }

    private uint _quality = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }

    private string _logicname = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"logicname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string logicname
    {
      get { return _logicname; }
      set { _logicname = value; }
    }

    private string _nametype = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"nametype", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nametype
    {
      get { return _nametype; }
      set { _nametype = value; }
    }

    private string _description = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }

    private int _distance = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int distance
    {
      get { return _distance; }
      set { _distance = value; }
    }

    private int _target = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }

    private int _attacktype = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"attacktype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attacktype
    {
      get { return _attacktype; }
      set { _attacktype = value; }
    }

    private int _release = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"release", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int release
    {
      get { return _release; }
      set { _release = value; }
    }

    private int _flight_speed = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"flight_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flight_speed
    {
      get { return _flight_speed; }
      set { _flight_speed = value; }
    }

    private int _scope = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"scope", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scope
    {
      get { return _scope; }
      set { _scope = value; }
    }

    private int _influence_number = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"influence_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int influence_number
    {
      get { return _influence_number; }
      set { _influence_number = value; }
    }

    private int _carry_level = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"carry_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int carry_level
    {
      get { return _carry_level; }
      set { _carry_level = value; }
    }

    private int _upgrade_level = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"upgrade_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int upgrade_level
    {
      get { return _upgrade_level; }
      set { _upgrade_level = value; }
    }

    private int _skill_addition = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"skill_addition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill_addition
    {
      get { return _skill_addition; }
      set { _skill_addition = value; }
    }

    private int _skill_addition_value = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"skill_addition_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill_addition_value
    {
      get { return _skill_addition_value; }
      set { _skill_addition_value = value; }
    }

    private int _skill_level_addition = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"skill_level_addition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill_level_addition
    {
      get { return _skill_level_addition; }
      set { _skill_level_addition = value; }
    }

    private int _skill_cd = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"skill_cd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill_cd
    {
      get { return _skill_cd; }
      set { _skill_cd = value; }
    }

    private int _buffid = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"buffid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buffid
    {
      get { return _buffid; }
      set { _buffid = value; }
    }

    private int _sell = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"sell", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sell
    {
      get { return _sell; }
      set { _sell = value; }
    }

    private int _quantity = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }

    private int _sell_royalty = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"sell_royalty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sell_royalty
    {
      get { return _sell_royalty; }
      set { _sell_royalty = value; }
    }

    private string _consumables = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"consumables", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string consumables
    {
      get { return _consumables; }
      set { _consumables = value; }
    }

    private string _consumables_quantity = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"consumables_quantity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string consumables_quantity
    {
      get { return _consumables_quantity; }
      set { _consumables_quantity = value; }
    }

    private string _consumables_quantity_royalty = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"consumables_quantity_royalty", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string consumables_quantity_royalty
    {
      get { return _consumables_quantity_royalty; }
      set { _consumables_quantity_royalty = value; }
    }

    private string _model = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string model
    {
      get { return _model; }
      set { _model = value; }
    }

    private string _icon = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }

    private string _sound = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"sound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sound
    {
      get { return _sound; }
      set { _sound = value; }
    }

    private string _preparations_attack = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"preparations_attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string preparations_attack
    {
      get { return _preparations_attack; }
      set { _preparations_attack = value; }
    }

    private string _attack_effect = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"attack_effect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string attack_effect
    {
      get { return _attack_effect; }
      set { _attack_effect = value; }
    }

    private string _gethit_effect = "";
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"gethit_effect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gethit_effect
    {
      get { return _gethit_effect; }
      set { _gethit_effect = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseSkill")]
  public partial class ResponseSkill : global::ProtoBuf.IExtensible
  {
    public ResponseSkill() {}
    
    private readonly global::System.Collections.Generic.List<clientmsg.SkillData> _skill_data = new global::System.Collections.Generic.List<clientmsg.SkillData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"skill_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<clientmsg.SkillData> skill_data
    {
      get { return _skill_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillbuffData")]
  public partial class SkillbuffData : global::ProtoBuf.IExtensible
  {
    public SkillbuffData() {}
    

    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private uint _location = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint location
    {
      get { return _location; }
      set { _location = value; }
    }

    private uint _number = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint number
    {
      get { return _number; }
      set { _number = value; }
    }

    private uint _advanced = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"advanced", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint advanced
    {
      get { return _advanced; }
      set { _advanced = value; }
    }

    private uint _quality = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _description = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }

    private string _effect = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"effect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string effect
    {
      get { return _effect; }
      set { _effect = value; }
    }

    private int _gain = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"gain", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gain
    {
      get { return _gain; }
      set { _gain = value; }
    }

    private int _bufftype = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"bufftype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bufftype
    {
      get { return _bufftype; }
      set { _bufftype = value; }
    }

    private int _skill_addition = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"skill_addition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill_addition
    {
      get { return _skill_addition; }
      set { _skill_addition = value; }
    }

    private int _skill_addition_value = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"skill_addition_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill_addition_value
    {
      get { return _skill_addition_value; }
      set { _skill_addition_value = value; }
    }

    private int _skill_level_addition = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"skill_level_addition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill_level_addition
    {
      get { return _skill_level_addition; }
      set { _skill_level_addition = value; }
    }

    private int _superposition = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"superposition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int superposition
    {
      get { return _superposition; }
      set { _superposition = value; }
    }

    private int _trigger_skillid = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"trigger_skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int trigger_skillid
    {
      get { return _trigger_skillid; }
      set { _trigger_skillid = value; }
    }

    private int _trigger_probability = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"trigger_probability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int trigger_probability
    {
      get { return _trigger_probability; }
      set { _trigger_probability = value; }
    }

    private string _logicname = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"logicname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string logicname
    {
      get { return _logicname; }
      set { _logicname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseSkillbuff")]
  public partial class ResponseSkillbuff : global::ProtoBuf.IExtensible
  {
    public ResponseSkillbuff() {}
    
    private readonly global::System.Collections.Generic.List<clientmsg.SkillbuffData> _skillbuff_data = new global::System.Collections.Generic.List<clientmsg.SkillbuffData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"skillbuff_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<clientmsg.SkillbuffData> skillbuff_data
    {
      get { return _skillbuff_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConfigData")]
  public partial class ConfigData : global::ProtoBuf.IExtensible
  {
    public ConfigData() {}
    

    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _configtype = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"configtype", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string configtype
    {
      get { return _configtype; }
      set { _configtype = value; }
    }

    private string _configlevel = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"configlevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string configlevel
    {
      get { return _configlevel; }
      set { _configlevel = value; }
    }

    private string _confignumber = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"confignumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string confignumber
    {
      get { return _confignumber; }
      set { _confignumber = value; }
    }

    private string _configname = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"configname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string configname
    {
      get { return _configname; }
      set { _configname = value; }
    }

    private string _configdesc = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"configdesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string configdesc
    {
      get { return _configdesc; }
      set { _configdesc = value; }
    }

    private uint _configquatity = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"configquatity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint configquatity
    {
      get { return _configquatity; }
      set { _configquatity = value; }
    }

    private uint _useconfiglevel = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"useconfiglevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint useconfiglevel
    {
      get { return _useconfiglevel; }
      set { _useconfiglevel = value; }
    }

    private uint _isuse = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isuse", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isuse
    {
      get { return _isuse; }
      set { _isuse = value; }
    }

    private uint _istrade = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"istrade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint istrade
    {
      get { return _istrade; }
      set { _istrade = value; }
    }

    private uint _isadd = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"isadd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isadd
    {
      get { return _isadd; }
      set { _isadd = value; }
    }

    private uint _maxaddnum = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"maxaddnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint maxaddnum
    {
      get { return _maxaddnum; }
      set { _maxaddnum = value; }
    }

    private uint _configattr = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"configattr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint configattr
    {
      get { return _configattr; }
      set { _configattr = value; }
    }

    private uint _upnum = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"upnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint upnum
    {
      get { return _upnum; }
      set { _upnum = value; }
    }

    private string _atlasname = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"atlasname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string atlasname
    {
      get { return _atlasname; }
      set { _atlasname = value; }
    }

    private string _picname = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"picname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string picname
    {
      get { return _picname; }
      set { _picname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseConfigData")]
  public partial class ResponseConfigData : global::ProtoBuf.IExtensible
  {
    public ResponseConfigData() {}
    
    private readonly global::System.Collections.Generic.List<clientmsg.ConfigData> _config_data = new global::System.Collections.Generic.List<clientmsg.ConfigData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"config_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<clientmsg.ConfigData> config_data
    {
      get { return _config_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FanPaiItemData")]
  public partial class FanPaiItemData : global::ProtoBuf.IExtensible
  {
    public FanPaiItemData() {}
    

    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private uint _itemstype = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemstype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemstype
    {
      get { return _itemstype; }
      set { _itemstype = value; }
    }

    private uint _itemslevel = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"itemslevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemslevel
    {
      get { return _itemslevel; }
      set { _itemslevel = value; }
    }

    private uint _itemsnum = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"itemsnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemsnum
    {
      get { return _itemsnum; }
      set { _itemsnum = value; }
    }

    private string _itemsname = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"itemsname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string itemsname
    {
      get { return _itemsname; }
      set { _itemsname = value; }
    }

    private string _itemsdesc = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"itemsdesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string itemsdesc
    {
      get { return _itemsdesc; }
      set { _itemsdesc = value; }
    }

    private uint _itemsquatity = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"itemsquatity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemsquatity
    {
      get { return _itemsquatity; }
      set { _itemsquatity = value; }
    }

    private uint _uselevel = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"uselevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uselevel
    {
      get { return _uselevel; }
      set { _uselevel = value; }
    }

    private uint _isuse = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isuse", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isuse
    {
      get { return _isuse; }
      set { _isuse = value; }
    }

    private uint _istrade = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"istrade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint istrade
    {
      get { return _istrade; }
      set { _istrade = value; }
    }

    private uint _isadd = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"isadd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isadd
    {
      get { return _isadd; }
      set { _isadd = value; }
    }

    private uint _maxaddnum = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"maxaddnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint maxaddnum
    {
      get { return _maxaddnum; }
      set { _maxaddnum = value; }
    }

    private uint _itemsattr = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"itemsattr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemsattr
    {
      get { return _itemsattr; }
      set { _itemsattr = value; }
    }

    private uint _upnum = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"upnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint upnum
    {
      get { return _upnum; }
      set { _upnum = value; }
    }

    private string _atlasname = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"atlasname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string atlasname
    {
      get { return _atlasname; }
      set { _atlasname = value; }
    }

    private string _picname = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"picname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string picname
    {
      get { return _picname; }
      set { _picname = value; }
    }

    private uint _weight = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"weight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint weight
    {
      get { return _weight; }
      set { _weight = value; }
    }

    private uint _amount = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseFanPaiItemData")]
  public partial class ResponseFanPaiItemData : global::ProtoBuf.IExtensible
  {
    public ResponseFanPaiItemData() {}
    
    private readonly global::System.Collections.Generic.List<clientmsg.FanPaiItemData> _item_data = new global::System.Collections.Generic.List<clientmsg.FanPaiItemData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<clientmsg.FanPaiItemData> item_data
    {
      get { return _item_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CumLoginRewardData")]
  public partial class CumLoginRewardData : global::ProtoBuf.IExtensible
  {
    public CumLoginRewardData() {}
    

    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _desc = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }

    private string _giftid = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"giftid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string giftid
    {
      get { return _giftid; }
      set { _giftid = value; }
    }

    private string _giftamount = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"giftamount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string giftamount
    {
      get { return _giftamount; }
      set { _giftamount = value; }
    }

    private uint _giftday = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"giftday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint giftday
    {
      get { return _giftday; }
      set { _giftday = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseCumLoginRewardData")]
  public partial class ResponseCumLoginRewardData : global::ProtoBuf.IExtensible
  {
    public ResponseCumLoginRewardData() {}
    
    private readonly global::System.Collections.Generic.List<clientmsg.CumLoginRewardData> _rewarddata = new global::System.Collections.Generic.List<clientmsg.CumLoginRewardData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rewarddata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<clientmsg.CumLoginRewardData> rewarddata
    {
      get { return _rewarddata; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestStageData")]
  public partial class RequestStageData : global::ProtoBuf.IExtensible
  {
    public RequestStageData() {}
    

    private uint _uaid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uaid
    {
      get { return _uaid; }
      set { _uaid = value; }
    }

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private uint _stageid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stageid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stageid
    {
      get { return _stageid; }
      set { _stageid = value; }
    }

    private uint _landingid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"landingid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint landingid
    {
      get { return _landingid; }
      set { _landingid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseStageData")]
  public partial class ResponseStageData : global::ProtoBuf.IExtensible
  {
    public ResponseStageData() {}
    

    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private uint _islandsid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"islandsid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint islandsid
    {
      get { return _islandsid; }
      set { _islandsid = value; }
    }

    private uint _landingid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"landingid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint landingid
    {
      get { return _landingid; }
      set { _landingid = value; }
    }

    private string _landingname = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"landingname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string landingname
    {
      get { return _landingname; }
      set { _landingname = value; }
    }

    private string _description = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }

    private uint _challenging = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"challenging", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint challenging
    {
      get { return _challenging; }
      set { _challenging = value; }
    }

    private uint _powerdeplete = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"powerdeplete", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint powerdeplete
    {
      get { return _powerdeplete; }
      set { _powerdeplete = value; }
    }

    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }

    private string _weather = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"weather", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string weather
    {
      get { return _weather; }
      set { _weather = value; }
    }

    private uint _lastblood = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"lastblood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lastblood
    {
      get { return _lastblood; }
      set { _lastblood = value; }
    }

    private uint _clearancetime = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"clearancetime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint clearancetime
    {
      get { return _clearancetime; }
      set { _clearancetime = value; }
    }

    private uint _expon_ship = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"expon_ship", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint expon_ship
    {
      get { return _expon_ship; }
      set { _expon_ship = value; }
    }

    private uint _expoff_ship = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"expoff_ship", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint expoff_ship
    {
      get { return _expoff_ship; }
      set { _expoff_ship = value; }
    }

    private uint _expon_crew = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"expon_crew", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint expon_crew
    {
      get { return _expon_crew; }
      set { _expon_crew = value; }
    }

    private uint _expoff_crew = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"expoff_crew", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint expoff_crew
    {
      get { return _expoff_crew; }
      set { _expoff_crew = value; }
    }

    private string _props = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"props", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string props
    {
      get { return _props; }
      set { _props = value; }
    }

    private uint _silveron_ship = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"silveron_ship", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint silveron_ship
    {
      get { return _silveron_ship; }
      set { _silveron_ship = value; }
    }

    private uint _silveroff_ship = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"silveroff_ship", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint silveroff_ship
    {
      get { return _silveroff_ship; }
      set { _silveroff_ship = value; }
    }

    private uint _honor = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"honor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint honor
    {
      get { return _honor; }
      set { _honor = value; }
    }

    private string _transport_pos = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"transport_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string transport_pos
    {
      get { return _transport_pos; }
      set { _transport_pos = value; }
    }

    private string _start_pos = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"start_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string start_pos
    {
      get { return _start_pos; }
      set { _start_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"FightT")]
    public enum FightT
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVE", Value=1)]
      PVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP", Value=2)]
      PVP = 2
    }
  
}