//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: map.proto
// Note: requires additional types generated from: common.proto
using common;
namespace clientmsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapScreenRefreshCharacter")]
  public partial class MapScreenRefreshCharacter : global::ProtoBuf.IExtensible
  {
    public MapScreenRefreshCharacter() {}
    

    private MapCharInfo _mapinfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapCharInfo mapinfo
    {
      get { return _mapinfo; }
      set { _mapinfo = value; }
    }

    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }

    private uint _cityid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cityid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cityid
    {
      get { return _cityid; }
      set { _cityid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapFreshSelf")]
  public partial class MapFreshSelf : global::ProtoBuf.IExtensible
  {
    public MapFreshSelf() {}
    

    private MapCharInfo _mapinfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapCharInfo mapinfo
    {
      get { return _mapinfo; }
      set { _mapinfo = value; }
    }

    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }

    private uint _cityid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cityid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cityid
    {
      get { return _cityid; }
      set { _cityid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NineScreenRefreshPlayer")]
  public partial class NineScreenRefreshPlayer : global::ProtoBuf.IExtensible
  {
    public NineScreenRefreshPlayer() {}
    
    private readonly global::System.Collections.Generic.List<MapCharInfo> _users = new global::System.Collections.Generic.List<MapCharInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapCharInfo> users
    {
      get { return _users; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharMove")]
  public partial class CharMove : global::ProtoBuf.IExtensible
  {
    public CharMove() {}
    

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private float _dir = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float dir
    {
      get { return _dir; }
      set { _dir = value; }
    }

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }

    private uint _speed = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint speed
    {
      get { return _speed; }
      set { _speed = value; }
    }

    private uint _timestamp = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharMoveFailed")]
  public partial class CharMoveFailed : global::ProtoBuf.IExtensible
  {
    public CharMoveFailed() {}
    

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }

    private uint _speed = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint speed
    {
      get { return _speed; }
      set { _speed = value; }
    }

    private float _dir = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float dir
    {
      get { return _dir; }
      set { _dir = value; }
    }

    private uint _timestamp = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapRemoveChar")]
  public partial class MapRemoveChar : global::ProtoBuf.IExtensible
  {
    public MapRemoveChar() {}
    
    private readonly global::System.Collections.Generic.List<uint> _users = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"users", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> users
    {
      get { return _users; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharChangeScene")]
  public partial class CharChangeScene : global::ProtoBuf.IExtensible
  {
    public CharChangeScene() {}
    

    private uint _cityid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cityid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cityid
    {
      get { return _cityid; }
      set { _cityid = value; }
    }

    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseChangeScene")]
  public partial class ResponseChangeScene : global::ProtoBuf.IExtensible
  {
    public ResponseChangeScene() {}
    

    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }

    private uint _cityid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cityid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cityid
    {
      get { return _cityid; }
      set { _cityid = value; }
    }

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }

    private clientmsg.enumChangeSceneResult _result = clientmsg.enumChangeSceneResult.enumChangeSceneResult_Success;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(clientmsg.enumChangeSceneResult.enumChangeSceneResult_Success)]
    public clientmsg.enumChangeSceneResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharGoTo")]
  public partial class CharGoTo : global::ProtoBuf.IExtensible
  {
    public CharGoTo() {}
    

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SMove")]
  public partial class C2SMove : global::ProtoBuf.IExtensible
  {
    public C2SMove() {}
    

    private uint _dir = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dir
    {
      get { return _dir; }
      set { _dir = value; }
    }

    private float _cur_x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cur_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cur_x
    {
      get { return _cur_x; }
      set { _cur_x = value; }
    }

    private float _cur_y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cur_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cur_y
    {
      get { return _cur_y; }
      set { _cur_y = value; }
    }

    private float _speed = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }

    private bool _need_broadcast = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"need_broadcast", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool need_broadcast
    {
      get { return _need_broadcast; }
      set { _need_broadcast = value; }
    }

    private ulong _time_stamp = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"time_stamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong time_stamp
    {
      get { return _time_stamp; }
      set { _time_stamp = value; }
    }

    private uint _mf = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mf
    {
      get { return _mf; }
      set { _mf = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CMove")]
  public partial class S2CMove : global::ProtoBuf.IExtensible
  {
    public S2CMove() {}
    

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private uint _dir = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dir
    {
      get { return _dir; }
      set { _dir = value; }
    }

    private float _pos_x = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }

    private float _pos_y = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }

    private float _speed = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }

    private ulong _time_stamp = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"time_stamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong time_stamp
    {
      get { return _time_stamp; }
      set { _time_stamp = value; }
    }

    private uint _mf = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mf
    {
      get { return _mf; }
      set { _mf = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SProofTime")]
  public partial class C2SProofTime : global::ProtoBuf.IExtensible
  {
    public C2SProofTime() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CProofTime")]
  public partial class S2CProofTime : global::ProtoBuf.IExtensible
  {
    public S2CProofTime() {}
    

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private ulong _time_stamp = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time_stamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong time_stamp
    {
      get { return _time_stamp; }
      set { _time_stamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestLevelMonster")]
  public partial class RequestLevelMonster : global::ProtoBuf.IExtensible
  {
    public RequestLevelMonster() {}
    

    private uint _levelid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"levelid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint levelid
    {
      get { return _levelid; }
      set { _levelid = value; }
    }

    private uint _landingid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"landingid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint landingid
    {
      get { return _landingid; }
      set { _landingid = value; }
    }

    private uint _enemygroupid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"enemygroupid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint enemygroupid
    {
      get { return _enemygroupid; }
      set { _enemygroupid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterData")]
  public partial class MonsterData : global::ProtoBuf.IExtensible
  {
    public MonsterData() {}
    

    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private uint _modelid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"modelid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint modelid
    {
      get { return _modelid; }
      set { _modelid = value; }
    }

    private string _monstername = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"monstername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string monstername
    {
      get { return _monstername; }
      set { _monstername = value; }
    }

    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private uint _basehp = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"basehp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint basehp
    {
      get { return _basehp; }
      set { _basehp = value; }
    }

    private uint _defence = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint defence
    {
      get { return _defence; }
      set { _defence = value; }
    }

    private uint _hit = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hit
    {
      get { return _hit; }
      set { _hit = value; }
    }

    private uint _dodge = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dodge
    {
      get { return _dodge; }
      set { _dodge = value; }
    }

    private uint _crit = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint crit
    {
      get { return _crit; }
      set { _crit = value; }
    }

    private uint _resist = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"resist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint resist
    {
      get { return _resist; }
      set { _resist = value; }
    }

    private uint _movespeed = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"movespeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint movespeed
    {
      get { return _movespeed; }
      set { _movespeed = value; }
    }

    private uint _turnspeed = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"turnspeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint turnspeed
    {
      get { return _turnspeed; }
      set { _turnspeed = value; }
    }

    private uint _apcc_normal = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"apcc_normal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint apcc_normal
    {
      get { return _apcc_normal; }
      set { _apcc_normal = value; }
    }

    private uint _apcc_normal_hurt = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"apcc_normal_hurt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint apcc_normal_hurt
    {
      get { return _apcc_normal_hurt; }
      set { _apcc_normal_hurt = value; }
    }

    private string _skill = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string skill
    {
      get { return _skill; }
      set { _skill = value; }
    }

    private string _skill_hurt = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"skill_hurt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string skill_hurt
    {
      get { return _skill_hurt; }
      set { _skill_hurt = value; }
    }

    private uint _apcc_gap = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"apcc_gap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint apcc_gap
    {
      get { return _apcc_gap; }
      set { _apcc_gap = value; }
    }

    private uint _gold = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private int _posx = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"posx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posx
    {
      get { return _posx; }
      set { _posx = value; }
    }

    private int _posy = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"posy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posy
    {
      get { return _posy; }
      set { _posy = value; }
    }

    private string _apcc_pos = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"apcc_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string apcc_pos
    {
      get { return _apcc_pos; }
      set { _apcc_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseLevelMonster")]
  public partial class ResponseLevelMonster : global::ProtoBuf.IExtensible
  {
    public ResponseLevelMonster() {}
    

    private uint _levelid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"levelid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint levelid
    {
      get { return _levelid; }
      set { _levelid = value; }
    }

    private uint _landingid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"landingid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint landingid
    {
      get { return _landingid; }
      set { _landingid = value; }
    }

    private uint _enemygroup = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"enemygroup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint enemygroup
    {
      get { return _enemygroup; }
      set { _enemygroup = value; }
    }

    private string _monsterpos = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"monsterpos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string monsterpos
    {
      get { return _monsterpos; }
      set { _monsterpos = value; }
    }

    private string _monstergroup = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"monstergroup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string monstergroup
    {
      get { return _monstergroup; }
      set { _monstergroup = value; }
    }
    private readonly global::System.Collections.Generic.List<clientmsg.MonsterData> _monsterlist = new global::System.Collections.Generic.List<clientmsg.MonsterData>();
    [global::ProtoBuf.ProtoMember(6, Name=@"monsterlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<clientmsg.MonsterData> monsterlist
    {
      get { return _monsterlist; }
    }
  

    private clientmsg.enumRequestLevelMonsterResult _result = clientmsg.enumRequestLevelMonsterResult.enumRequestLevelMonsterResult_Success;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(clientmsg.enumRequestLevelMonsterResult.enumRequestLevelMonsterResult_Success)]
    public clientmsg.enumRequestLevelMonsterResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestLevelItem")]
  public partial class RequestLevelItem : global::ProtoBuf.IExtensible
  {
    public RequestLevelItem() {}
    

    private uint _levelid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"levelid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint levelid
    {
      get { return _levelid; }
      set { _levelid = value; }
    }

    private uint _landingid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"landingid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint landingid
    {
      get { return _landingid; }
      set { _landingid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestCharPackage")]
  public partial class RequestCharPackage : global::ProtoBuf.IExtensible
  {
    public RequestCharPackage() {}
    

    private uint _uaid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uaid
    {
      get { return _uaid; }
      set { _uaid = value; }
    }

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestChangePackage")]
  public partial class RequestChangePackage : global::ProtoBuf.IExtensible
  {
    public RequestChangePackage() {}
    

    private uint _uaid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uaid
    {
      get { return _uaid; }
      set { _uaid = value; }
    }

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private uint _itemid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }

    private uint _itemtype = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"itemtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemtype
    {
      get { return _itemtype; }
      set { _itemtype = value; }
    }

    private uint _itemnum = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"itemnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemnum
    {
      get { return _itemnum; }
      set { _itemnum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseCharPackage")]
  public partial class ResponseCharPackage : global::ProtoBuf.IExtensible
  {
    public ResponseCharPackage() {}
    

    private string _content = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseChangePackage")]
  public partial class ResponseChangePackage : global::ProtoBuf.IExtensible
  {
    public ResponseChangePackage() {}
    

    private string _content = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"enumChangeSceneResult")]
    public enum enumChangeSceneResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumChangeSceneResult_Success", Value=1)]
      enumChangeSceneResult_Success = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumChangeSceneResult_NotScene", Value=2)]
      enumChangeSceneResult_NotScene = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"enumRequestLevelMonsterResult")]
    public enum enumRequestLevelMonsterResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumRequestLevelMonsterResult_Success", Value=1)]
      enumRequestLevelMonsterResult_Success = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumRequestLevelMonsterResult_NotMonster", Value=2)]
      enumRequestLevelMonsterResult_NotMonster = 2
    }
  
}