//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: servercommon.proto
// Note: requires additional types generated from: common.proto
using common;
namespace servermsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharServerInfo")]
  public partial class CharServerInfo : global::ProtoBuf.IExtensible
  {
    public CharServerInfo() {}
    

    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }

    private uint _cityid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cityid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cityid
    {
      get { return _cityid; }
      set { _cityid = value; }
    }

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerLoginRequest")]
  public partial class ServerLoginRequest : global::ProtoBuf.IExtensible
  {
    public ServerLoginRequest() {}
    

    private uint _servertype = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"servertype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint servertype
    {
      get { return _servertype; }
      set { _servertype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerInfo")]
  public partial class ServerInfo : global::ProtoBuf.IExtensible
  {
    public ServerInfo() {}
    

    private int _kind = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"kind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int kind
    {
      get { return _kind; }
      set { _kind = value; }
    }

    private uint _uuid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private uint _group = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint group
    {
      get { return _group; }
      set { _group = value; }
    }

    private string _address = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }

    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerLoginResponse")]
  public partial class ServerLoginResponse : global::ProtoBuf.IExtensible
  {
    public ServerLoginResponse() {}
    

    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private uint _group = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint group
    {
      get { return _group; }
      set { _group = value; }
    }

    private uint _uuid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _address = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }

    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private readonly global::System.Collections.Generic.List<servermsg.ServerInfo> _serverlist = new global::System.Collections.Generic.List<servermsg.ServerInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"serverlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<servermsg.ServerInfo> serverlist
    {
      get { return _serverlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginSessionRegistRequest")]
  public partial class LoginSessionRegistRequest : global::ProtoBuf.IExtensible
  {
    public LoginSessionRegistRequest() {}
    

    private ulong _user_account = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }

    private string _session = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string session
    {
      get { return _session; }
      set { _session = value; }
    }

    private uint _oid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint oid
    {
      get { return _oid; }
      set { _oid = value; }
    }

    private byte[] _username = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] username
    {
      get { return _username; }
      set { _username = value; }
    }

    private byte[] _charname = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"charname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] charname
    {
      get { return _charname; }
      set { _charname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerLoginNotify")]
  public partial class ServerLoginNotify : global::ProtoBuf.IExtensible
  {
    public ServerLoginNotify() {}
    

    private string _address = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }

    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }

    private uint _group = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint group
    {
      get { return _group; }
      set { _group = value; }
    }

    private uint _uuid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private uint _kind = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"kind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint kind
    {
      get { return _kind; }
      set { _kind = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginSessionRegistResponse")]
  public partial class LoginSessionRegistResponse : global::ProtoBuf.IExtensible
  {
    public LoginSessionRegistResponse() {}
    

    private ulong _user_account = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }

    private string _session = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string session
    {
      get { return _session; }
      set { _session = value; }
    }

    private uint _oid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint oid
    {
      get { return _oid; }
      set { _oid = value; }
    }

    private byte[] _username = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] username
    {
      get { return _username; }
      set { _username = value; }
    }

    private byte[] _charname = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"charname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] charname
    {
      get { return _charname; }
      set { _charname = value; }
    }

    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private string _address = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }

    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GateSessionCheckRequest")]
  public partial class GateSessionCheckRequest : global::ProtoBuf.IExtensible
  {
    public GateSessionCheckRequest() {}
    

    private ulong _user_account = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }

    private uint _gate_oid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gate_oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gate_oid
    {
      get { return _gate_oid; }
      set { _gate_oid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GateSessionCheckResponse")]
  public partial class GateSessionCheckResponse : global::ProtoBuf.IExtensible
  {
    public GateSessionCheckResponse() {}
    

    private servermsg.enumSessionCheckResponse _result = servermsg.enumSessionCheckResponse.enumSessionCheck_Success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(servermsg.enumSessionCheckResponse.enumSessionCheck_Success)]
    public servermsg.enumSessionCheckResponse result
    {
      get { return _result; }
      set { _result = value; }
    }

    private uint _gate_oid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gate_oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gate_oid
    {
      get { return _gate_oid; }
      set { _gate_oid = value; }
    }

    private ulong _user_account = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }

    private uint _uuid_gameserver = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"uuid_gameserver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uuid_gameserver
    {
      get { return _uuid_gameserver; }
      set { _uuid_gameserver = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestCharInfoFromDB")]
  public partial class RequestCharInfoFromDB : global::ProtoBuf.IExtensible
  {
    public RequestCharInfoFromDB() {}
    

    private ulong _user_account = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }

    private uint _gateid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gateid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gateid
    {
      get { return _gateid; }
      set { _gateid = value; }
    }

    private uint _gate_network = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gate_network", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gate_network
    {
      get { return _gate_network; }
      set { _gate_network = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DBResponseCharInfo")]
  public partial class DBResponseCharInfo : global::ProtoBuf.IExtensible
  {
    public DBResponseCharInfo() {}
    

    private ulong _user_account = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }

    private uint _gateid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gateid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gateid
    {
      get { return _gateid; }
      set { _gateid = value; }
    }

    private uint _gate_network = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gate_network", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gate_network
    {
      get { return _gate_network; }
      set { _gate_network = value; }
    }

    private CharInfo _charinfo = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"charinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CharInfo charinfo
    {
      get { return _charinfo; }
      set { _charinfo = value; }
    }

    private servermsg.CharServerInfo _charserverinfo = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"charserverinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public servermsg.CharServerInfo charserverinfo
    {
      get { return _charserverinfo; }
      set { _charserverinfo = value; }
    }

    private common.enumGetCharResult _result = common.enumGetCharResult.Response_NewChar;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(common.enumGetCharResult.Response_NewChar)]
    public common.enumGetCharResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DBSaveCharInfo")]
  public partial class DBSaveCharInfo : global::ProtoBuf.IExtensible
  {
    public DBSaveCharInfo() {}
    

    private uint _savetype = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"savetype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint savetype
    {
      get { return _savetype; }
      set { _savetype = value; }
    }

    private CharInfo _charinfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CharInfo charinfo
    {
      get { return _charinfo; }
      set { _charinfo = value; }
    }

    private servermsg.CharServerInfo _charserverinfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"charserverinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public servermsg.CharServerInfo charserverinfo
    {
      get { return _charserverinfo; }
      set { _charserverinfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginCenter")]
  public partial class LoginCenter : global::ProtoBuf.IExtensible
  {
    public LoginCenter() {}
    

    private ulong _user_account = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }

    private uint _gate_oid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gate_oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gate_oid
    {
      get { return _gate_oid; }
      set { _gate_oid = value; }
    }

    private common.enumCharType _type = common.enumCharType.enumChar_Company;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(common.enumCharType.enumChar_Company)]
    public common.enumCharType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Updatemapinfotoserver")]
  public partial class Updatemapinfotoserver : global::ProtoBuf.IExtensible
  {
    public Updatemapinfotoserver() {}
    

    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"enumSessionCheckResponse")]
    public enum enumSessionCheckResponse
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumSessionCheck_Success", Value=0)]
      enumSessionCheck_Success = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumSessionCheck_LoginFailed", Value=1)]
      enumSessionCheck_LoginFailed = 1
    }
  
}